"""

DMX Address Calculator
Author: Sebastiaan de Rooij
Version: 0.1.0

contains the logic for the DMX address calculator

Inputs are assumed validated by the frontend layer.
Backend does not perform type validation (V2 design choice).

a table is generated by a 'list of lists' populated via the entered data and a loop

the print functions are for testing purposes and will be commented out

"""

VERSION = "0.1.1"

group_name = "group 1"
universe = 1
universe_size = 512
first_fixture_nr = 1
first_address = 1
nr_of_channels = 1
nr_of_fixtures = 1


def check_range(first_address, nr_of_channels, nr_of_fixtures, universe_size):
    range_warning = False
    if first_address + nr_of_fixtures * nr_of_channels - 1 > universe_size:
        range_warning = True
    return range_warning


def generate_address_table(
    group_name,
    first_fixture_nr,
    universe,
    first_address,
    nr_of_channels,
    nr_of_fixtures,
):

    table = []
    current_fixture = first_fixture_nr
    current_address = first_address

    while current_fixture <= first_fixture_nr + nr_of_fixtures - 1:
        current_row = [
            group_name,
            current_fixture,
            "uni",
            universe,
            "ch",
            current_address,
        ]  # refactor to dictionary in next version
        table.append(current_row)
        current_fixture += 1
        current_address += nr_of_channels
    return table


def calculate_last_channel(first_address, nr_of_channels, nr_of_fixtures):
    last_channel_used = first_address + nr_of_fixtures * nr_of_channels - 1
    return last_channel_used


def print_table(address_table):
    for cell in address_table:
        print(cell[0], cell[1], cell[2], cell[3], cell[4], cell[5])


def print_last_channel(last_channel):
    print(f"last used channel: {last_channel}")


if __name__ == "__main__":
    # now this code only runs when run directly, not when imported as a module, research a bit!
    range_warning = check_range(
        first_address, nr_of_channels, nr_of_fixtures, universe_size
    )

    address_table = generate_address_table(
        group_name,
        first_fixture_nr,
        universe,
        first_address,
        nr_of_channels,
        nr_of_fixtures,
    )
    last_channel = calculate_last_channel(first_address, nr_of_channels, nr_of_fixtures)

    if range_warning:
        print("out of range")
    else:
        print_table(address_table)
        print_last_channel(last_channel)
